// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDCXxcS_e7RAKGdqD5trkKDrLszR8PK2DA',
    appId: '1:731560323593:android:d8081fc81ce210336926d8',
    messagingSenderId: '731560323593',
    projectId: 'searchy-1baa5',
    databaseURL: 'https://searchy-1baa5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'searchy-1baa5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM4IoMNJ0wOW7RFT_kxwBERguL1GNCaQg',
    appId: '1:731560323593:ios:bfc6451885c5a9716926d8',
    messagingSenderId: '731560323593',
    projectId: 'searchy-1baa5',
    databaseURL: 'https://searchy-1baa5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'searchy-1baa5.firebasestorage.app',
    iosBundleId: 'com.searchydict.searchyDict',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM4IoMNJ0wOW7RFT_kxwBERguL1GNCaQg',
    appId: '1:731560323593:ios:bfc6451885c5a9716926d8',
    messagingSenderId: '731560323593',
    projectId: 'searchy-1baa5',
    databaseURL: 'https://searchy-1baa5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'searchy-1baa5.firebasestorage.app',
    iosBundleId: 'com.searchydict.searchyDict',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA9yaO9dmLIkTiLNZ0BbthFupkTcFAAoLw',
    appId: '1:731560323593:web:e377ea2d126b51436926d8',
    messagingSenderId: '731560323593',
    projectId: 'searchy-1baa5',
    authDomain: 'searchy-1baa5.firebaseapp.com',
    databaseURL: 'https://searchy-1baa5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'searchy-1baa5.firebasestorage.app',
    measurementId: 'G-HZFHYNWX4T',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA9yaO9dmLIkTiLNZ0BbthFupkTcFAAoLw',
    appId: '1:731560323593:web:e377ea2d126b51436926d8',
    messagingSenderId: '731560323593',
    projectId: 'searchy-1baa5',
    authDomain: 'searchy-1baa5.firebaseapp.com',
    databaseURL: 'https://searchy-1baa5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'searchy-1baa5.firebasestorage.app',
    measurementId: 'G-HZFHYNWX4T',
  );

}